/*starts sequence at 10 to ensure valid id for special freetext entered manufacturer */
create sequence ID_MASTER_SEQ start 10 increment 50;
create table age (id int8 not null, version int4 not null, description varchar(255) not null, surveyIdentifier varchar(255) not null, value varchar(255) not null, primary key (id));
create table app (id int8 not null, version int4 not null, name varchar(255) not null, primary key (id));
create table captureddatacontrol (id int8 not null, version int4 not null, description varchar(255) not null, surveyIdentifier varchar(255) not null, value varchar(255) not null, primary key (id));
create table dataprivacyconcern (id int8 not null, version int4 not null, description varchar(255) not null, surveyIdentifier varchar(255) not null, value varchar(255) not null, primary key (id));
create table datareliability (id int8 not null, version int4 not null, description varchar(255) not null, surveyIdentifier varchar(255) not null, value varchar(255) not null, primary key (id));
create table datasharing (id int8 not null, version int4 not null, description varchar(255) not null, surveyIdentifier varchar(255) not null, value varchar(255) not null, primary key (id));
create table device (id int8 not null, version int4 not null, name varchar(255) not null, releaseDate date, deviceType_id int8, manufacturer_id int8, primary key (id));
create table devicerecord (id int8 not null, version int4 not null, recordType varchar(255), recordedValue float8, device_id int8, participant_id int8, primary key (id));
create table devicerecord_app (DeviceRecord_id int8 not null, apps_id int8 not null, primary key (DeviceRecord_id, apps_id));
create table devicetype (id int8 not null, version int4 not null, description varchar(255) not null, surveyIdentifier varchar(255) not null, value varchar(255) not null, primary key (id));
create table event (id int8 not null, version int4 not null, date date, description varchar(255), distance float8 not null, name varchar(255) not null, primary key (id));
create table gender (id int8 not null, version int4 not null, description varchar(255) not null, surveyIdentifier varchar(255) not null, value varchar(255) not null, primary key (id));
create table manufacturer (id int8 not null, version int4 not null, identity varchar(255) not null, primary key (id));
create table nousage (id int8 not null, version int4 not null, description varchar(255) not null, surveyIdentifier varchar(255) not null, value varchar(255) not null, primary key (id));
create table participant (id int8 not null, version int4 not null, activityCount int4, deviceCount int4, identity varchar(255) not null, age_id int8, dataPrivacyConcern_id int8, dataReliability_id int8, gender_id int8, primary key (id));
create table participant_captureddatacontrol (Participant_id int8 not null, captureDataControl_id int8 not null, primary key (Participant_id, captureDataControl_id));
create table participant_datasharing (Participant_id int8 not null, dataSharing_id int8 not null, primary key (Participant_id, dataSharing_id));
create table participant_nousage (Participant_id int8 not null, noUsages_id int8 not null, primary key (Participant_id, noUsages_id));
create table participant_technologymotivation (Participant_id int8 not null, technologyMotivation_id int8 not null, primary key (Participant_id, technologyMotivation_id));
create table participantsurveyrecord (id int8 not null, version int4 not null, questionnaireIdentifier varchar(255) not null, surveyType varchar(255), event_id int8, participant_id int8, primary key (id));
create table technologymotivation (id int8 not null, version int4 not null, description varchar(255) not null, surveyIdentifier varchar(255) not null, value varchar(255) not null, primary key (id));
create index age_survey_id_idx on age (surveyIdentifier);
create index age_value_idx on age (value);
alter table age add constraint UK_pdsfl5deqc1c30loawd2c1loj unique (surveyIdentifier);
create index app_name_idx on app (name);
alter table app add constraint UK_88vfgccvckwwip06k7tpf8uk3 unique (name);
create index captureddatacontrol_survey_id_idx on captureddatacontrol (surveyIdentifier);
create index captureddatacontrol_value_idx on captureddatacontrol (value);
alter table captureddatacontrol add constraint UK_9t8j21g0wntfxo1cw43poxwlg unique (surveyIdentifier);
create index dataprivacyconcern_survey_id_idx on dataprivacyconcern (surveyIdentifier);
create index dataprivacyconcern_value_idx on dataprivacyconcern (value);
alter table dataprivacyconcern add constraint UK_aytyod3y1pyr79pkk82qu1nf6 unique (surveyIdentifier);
create index datareliability_survey_id_idx on datareliability (surveyIdentifier);
create index datareliability_value_idx on datareliability (value);
alter table datareliability add constraint UK_d8n4hd3vs5rcjtfvtiwqhf5kh unique (surveyIdentifier);
create index datasharing_survey_id_idx on datasharing (surveyIdentifier);
create index datasharing_value_idx on datasharing (value);
alter table datasharing add constraint UK_c2i0ac9xwsb9we88hlqsrr5ic unique (surveyIdentifier);
create index device_name_idx on device (name);
create index device_manufacturer_idx on device (manufacturer_id);
create index device_device_type_idx on device (deviceType_id);
alter table device add constraint UK_oesoxj95nuiic4anb0i5fh9b1 unique (name);
create index devicerecord_partcipant_idx on devicerecord (participant_id);
create index devicerecord_device_idx on devicerecord (device_id);
create index devicetype_survey_id_idx on devicetype (surveyIdentifier);
create index devicetype_value_idx on devicetype (value);
alter table devicetype add constraint UK_7q0gwpic9efpljhqq6n53u1na unique (surveyIdentifier);
create index event_name_idx on event (name);
create index gender_survey_id_idx on gender (surveyIdentifier);
create index gender_value_idx on gender (value);
alter table gender add constraint UK_3akn84vrlh1b3vcnwu1p4lx62 unique (surveyIdentifier);
create index manufacturer_identity_idx on manufacturer (identity);
alter table manufacturer add constraint UK_b1le6uk9qejp68ejtujy8v9fj unique (identity);
create index nousage_survey_id_idx on nousage (surveyIdentifier);
create index nousageg_value_idx on nousage (value);
alter table nousage add constraint UK_9xywv11b05nfor6v2c8ffowbo unique (surveyIdentifier);
create index participant_age_idx on participant (age_id);
create index participant_gender_idx on participant (gender_id);
create index participant_identity_idx on participant (identity);
create index participant_reliability_idx on participant (dataReliability_id);
create index participant_dataprivacyconcern_idx on participant (dataPrivacyConcern_id);
alter table participant add constraint UK_a5l5h9qx0qdg64c8mt1ruo201 unique (identity);
create index participantsurveyrecord_participant_idx on participantsurveyrecord (participant_id);
create index participantsurveyrecord_event_idx on participantsurveyrecord (event_id);
create index participantsurveyrecord_questionnaireidentifier_idx on participantsurveyrecord (questionnaireIdentifier);
alter table participantsurveyrecord add constraint UK_e1f5iv8y36ijtbp3r6dl7jxa7 unique (questionnaireIdentifier);
create index technologymotivation_survey_id_idx on technologymotivation (surveyIdentifier);
create index technologymotivation_value_idx on technologymotivation (value);
alter table technologymotivation add constraint UK_3tc3m6h41dhobdv6bew0ybr4h unique (surveyIdentifier);
alter table device add constraint FKbodt5j27x0f03vb95stedyv5x foreign key (deviceType_id) references devicetype;
alter table device add constraint FKriee84evn29ma5ohx1lfbo436 foreign key (manufacturer_id) references manufacturer;
alter table devicerecord add constraint FKt89ptv2971sbe5ohnl3dd6w4q foreign key (device_id) references device;
alter table devicerecord add constraint FKesd3loq4245cg9xtex8xkw849 foreign key (participant_id) references participant;
alter table devicerecord_app add constraint FKlphr8g9ixhko9b3os2f7b0mbw foreign key (apps_id) references app;
alter table devicerecord_app add constraint FKf0tme6fxwbp28ien2u2cvivd3 foreign key (DeviceRecord_id) references devicerecord;
alter table participant add constraint FKo920fpgafrunudag59p2re7rk foreign key (age_id) references age;
alter table participant add constraint FKetocdyw1h1l40qhvh63u8px5q foreign key (dataPrivacyConcern_id) references dataprivacyconcern;
alter table participant add constraint FKted3vnog7ynkfavgi91d34221 foreign key (dataReliability_id) references datareliability;
alter table participant add constraint FK2kbisk0ju30xv19gkyh47bnw5 foreign key (gender_id) references gender;
alter table participant_captureddatacontrol add constraint FKgq3abo1h3u9nt2pr2epj5o3ug foreign key (captureDataControl_id) references captureddatacontrol;
alter table participant_captureddatacontrol add constraint FKc2ktvf2p2jip1qkbstkdh3rs8 foreign key (Participant_id) references participant;
alter table participant_datasharing add constraint FKghnitwtxioam239omhrufyx2i foreign key (dataSharing_id) references datasharing;
alter table participant_datasharing add constraint FKf5i532pphjavn84vo16qkv17l foreign key (Participant_id) references participant;
alter table participant_nousage add constraint FKok3bt0thoghxhaynw8heurejw foreign key (noUsages_id) references nousage;
alter table participant_nousage add constraint FKnvwnwtca3tfbmvld3u4hlfn6l foreign key (Participant_id) references participant;
alter table participant_technologymotivation add constraint FKjmyubm5fv5up6hieavna0evts foreign key (technologyMotivation_id) references technologymotivation;
alter table participant_technologymotivation add constraint FKn6bxvj1rg5tk9wkqeao6620ow foreign key (Participant_id) references participant;
alter table participantsurveyrecord add constraint FKrwq4ja8hy3yuxutwovaed63uj foreign key (event_id) references event;
alter table participantsurveyrecord add constraint FKaqvbmf07lvbrv9cnyrvu2pj86 foreign key (participant_id) references participant;
